name: Lint and Type Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -a
      - name: Setup
        uses: ./.github/actions/setup/action.yaml
      - name: Linting
        run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/action.yaml
      - name: Type checking
        run: npm run type:check
