name: Lint and Type Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          ls -a
          pwd
          cd ./.github/actions/setup
          ls
      - name: Setup
        uses: ./.github/actions/setup/action.yaml@609182b0f9ff3d09ed207528fdb509cc70e29555
      - name: Linting
        run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/action.yaml@609182b0f9ff3d09ed207528fdb509cc70e29555
      - name: Type checking
        run: npm run type:check
