name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  playwright-e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Debug Git Branches
        run: |
          echo "Before fetching:"
          git branch -a
          git fetch origin
          echo "After fetching:"
          git branch -a

      - name: Retrieve Allure History
        run: |
          # Fetch and check out allure-history
          git fetch origin allure-history
          git checkout allure-history
          mkdir -p allure-results
          cp -r ./reports/allure/history allure-results/history || echo "No history to copy"
          git checkout remotes/origin/main

          # Return to the original branch
          # ORIGINAL_BRANCH="${GITHUB_REF##*/}"
          # echo "Original branch: $ORIGINAL_BRANCH"
          # git fetch origin $ORIGINAL_BRANCH:$ORIGINAL_BRANCH || echo "Branch '$ORIGINAL_BRANCH' not found"
          # git checkout $ORIGINAL_BRANCH || echo "Failed to switch back to branch '$ORIGINAL_BRANCH'"

      - name: Debug Git Branches
        run: |
          echo "Before fetching:"
          git branch -a
          git fetch origin
          echo "After fetching:"
          git branch -a

      - name: Run Playwright tests
        run: npm run test --ignore-scripts
        env:
          BASE_URL_STAGE: ${{ secrets.BASE_URL_STAGE }}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Generate Allure report
        run: |
          npm i -g allure-commandline
          allure generate --clean -o reports/allure

      - name: Push report to history branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Check initial content of history directory
          echo "Before moving files:"
          ls -l reports/allure/history

          # Create temporary directory and verify
          mkdir -p ./history-backup
          ls -ld /history-backup

          # Move files to the temporary directory
          mv reports/allure/history/* /history-backup/
          echo "After moving files to /history-backup:"
          cd /tmp
          ls
          cd history-backup
          ls
          ls -l /history-backup

          # Recheck original directory
          echo "After moving, original directory state:"
          ls -l reports/allure/history-backup

          git fetch origin allure-history
          git checkout allure-history
          ls -a
          mv -f /history-backup/* /reports/allure/history/
          git add ./reports/allure/history
          git commit -m "Update report history"
          git push --force origin allure-history

      - name: Upload report to artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: reports
          path: reports/
          retention-days: 1

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: tests-report
          publish_dir: reports
