name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  playwright-e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Retrieve Allure History
        run: |
          git fetch origin allure-history
          git checkout allure-history
          mkdir -p allure-results
          cp -r reports/allure/history allure-results || echo "No history to copy"
          ls allure-results
          git checkout remotes/origin/main

      - name: Run Playwright tests
        run: npm run test --ignore-scripts
        env:
          BASE_URL_STAGE: ${{ secrets.BASE_URL_STAGE }}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Generate Allure report
        run: |
          npm i -g allure-commandline
          allure generate --clean -o reports/allure

      - name: Upload report to artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: reports
          path: reports/
          retention-days: 1

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: tests-report
          publish_dir: reports

      - name: Push report to history branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          mkdir -p history-backup
          mv reports/allure/history/* history-backup/

          git fetch origin allure-history
          git checkout allure-history
          mv -f ./history-backup/* ./reports/allure/history
          git add ./reports/allure/history
          git commit -m "Update report history"
          git push --force origin allure-history
