name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  playwright-e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HISTORY_BRANCH: allure-history
      REPORT_BRANCH: tests-report
      RESULTS_DIR: allure-results
      REPORTS_DIR: reports

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Retrieve Allure History
        run: |
          git fetch origin $HISTORY_BRANCH
          git checkout $HISTORY_BRANCH
          mkdir -p $RESULTS_DIR
          cp -r $REPORTS_DIR/allure/history $RESULTS_DIR
          ORIGINAL_BRANCH="${GITHUB_REF#refs/}"
          git fetch origin $ORIGINAL_BRANCH
          git checkout $ORIGINAL_BRANCH

      - name: Run Playwright tests
        run: npm run test --ignore-scripts
        env:
          BASE_URL_STAGE: ${{ secrets.BASE_URL_STAGE }}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Generate Allure report
        run: |
          npm i -g allure-commandline
          allure generate --clean -o $REPORTS_DIR/allure

      - name: Upload report to artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: $REPORTS_DIR
          path: $REPORTS_DIR/
          retention-days: 1

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ env.REPORT_BRANCH }}
          publish_dir: $REPORTS_DIR

      - name: Push report to history branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          mkdir -p history-backup
          mv $REPORTS_DIR/allure/history/* history-backup/
          git fetch origin $HISTORY_BRANCH
          git checkout $HISTORY_BRANCH
          mv -f ./history-backup/* ./$REPORTS_DIR/allure/history
          git add ./$REPORTS_DIR/allure/history
          git commit -m "Update report history"
          git push --force origin $HISTORY_BRANCH
